// lib/market-data.ts

export const INDICES = [
    // Benchmark Indices
    { name: 'NIFTY 50', ticker: '^NSEI' },
    { name: 'SENSEX', ticker: '^BSESN' },
    { name: 'INDIA VIX', ticker: '^INDIAVIX' },
    
    // Broader Market
    { name: 'NIFTY MIDCAP 100', ticker: 'NIFTY_MIDCAP_100.NS' },
    { name: 'NIFTY SMALLCAP 100', ticker: '^CNXSC' },

    // Sectoral Indices (From your list)
    { name: 'NIFTY BANK', ticker: '^NSEBANK' },
    { name: 'NIFTY AUTO', ticker: '^CNXAUTO' },
    { name: 'NIFTY IT', ticker: '^CNXIT' },
    { name: 'NIFTY FMCG', ticker: '^CNXFMCG' },
    { name: 'NIFTY METAL', ticker: '^CNXMETAL' },
    { name: 'NIFTY PHARMA', ticker: '^CNXPHARMA' },
    { name: 'NIFTY ENERGY', ticker: '^CNXENERGY' }, // Requested
    { name: 'NIFTY REALTY', ticker: '^CNXREALTY' },
    { name: 'NIFTY MEDIA', ticker: '^CNXMEDIA' },
    { name: 'NIFTY PSU BANK', ticker: '^CNXPSUBANK' },
    { name: 'NIFTY PVT BANK', ticker: 'NIFTY_PVT_BANK.NS' },
    { name: 'NIFTY HEALTHCARE', ticker: 'NIFTY_HEALTHCARE.NS' },
    { name: 'NIFTY CONSUMER DURABLES', ticker: '^CNXCONSUM' },
    { name: 'NIFTY FIN SERVICE', ticker: '^CNXFIN' },
]

// Full constituent lists for each index
export const SECTOR_CONSTITUENTS: Record<string, string[]> = {
    // --- BENCHMARKS ---
    '^INDIAVIX': [], // VIX has no constituents
    
    // SENSEX (Full 30)
    '^BSESN': [ 
        'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 'INFY.NS', 'HINDUNILVR.NS', 'ITC.NS', 'SBIN.NS', 
        'BHARTIARTL.NS', 'BAJFINANCE.NS', 'LT.NS', 'KOTAKBANK.NS', 'AXISBANK.NS', 'HCLTECH.NS', 'TITAN.NS', 
        'ASIANPAINT.NS', 'MARUTI.NS', 'SUNPHARMA.NS', 'TATASTEEL.NS', 'NTPC.NS', 'ULTRACEMCO.NS', 'POWERGRID.NS', 
        'M&M.NS', 'NESTLEIND.NS', 'TATAMOTORS.NS', 'INDUSINDBK.NS', 'TECHM.NS', 'WIPRO.NS', 'JSWSTEEL.NS', 'BAJAJFINSV.NS'
    ],

    // NIFTY 50 (Full List)
    '^NSEI': [ 
        'ADANIENT.NS', 'ADANIPORTS.NS', 'APOLLOHOSP.NS', 'ASIANPAINT.NS', 'AXISBANK.NS', 'BAJAJ-AUTO.NS', 
        'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'BPCL.NS', 'BHARTIARTL.NS', 'BRITANNIA.NS', 'CIPLA.NS', 'COALINDIA.NS', 
        'DIVISLAB.NS', 'DRREDDY.NS', 'EICHERMOT.NS', 'GRASIM.NS', 'HCLTECH.NS', 'HDFCBANK.NS', 'HDFCLIFE.NS', 
        'HEROMOTOCO.NS', 'HINDALCO.NS', 'HINDUNILVR.NS', 'ICICIBANK.NS', 'ITC.NS', 'INDUSINDBK.NS', 'INFY.NS', 
        'JSWSTEEL.NS', 'KOTAKBANK.NS', 'LTIM.NS', 'LT.NS', 'M&M.NS', 'MARUTI.NS', 'NESTLEIND.NS', 'NTPC.NS', 
        'ONGC.NS', 'POWERGRID.NS', 'RELIANCE.NS', 'SBILIFE.NS', 'SHRIRAMFIN.NS', 'SBIN.NS', 'SUNPHARMA.NS', 
        'TCS.NS', 'TATACONSUM.NS', 'TATAMOTORS.NS', 'TATASTEEL.NS', 'TECHM.NS', 'TITAN.NS', 'ULTRACEMCO.NS', 'WIPRO.NS'
    ],

    // --- BROADER MARKETS ---
    
    // NIFTY MIDCAP 100 (Major High Volume Constituents)
    'NIFTY_MIDCAP_100.NS': [
        '360ONE.NS', 'ACC.NS', 'APLAPOLLO.NS', 'AUBANK.NS', 'ATGL.NS', 'ABCAPITAL.NS', 'ALKEM.NS', 'ASHOKLEY.NS', 'ASTRAL.NS', 'AUROPHARMA.NS', 'BSE.NS', 'BANKINDIA.NS', 'BDL.NS', 'BHARATFORG.NS', 'BHEL.NS', 'BHARTIHEXA.NS', 'BIOCON.NS', 'BLUESTARCO.NS', 'COCHINSHIP.NS', 'COFORGE.NS', 'COLPAL.NS', 'CONCOR.NS', 'COROMANDEL.NS', 'CUMMINSIND.NS', 'DABUR.NS', 'DIXON.NS', 'EXIDEIND.NS', 'NYKAA.NS', 'FEDERALBNK.NS', 'FORTIS.NS', 'GMRAIRPORT.NS', 'GLENMARK.NS', 'GODFRYPHLP.NS', 'GODREJPROP.NS', 'HDFCAMC.NS', 'HEROMOTOCO.NS', 'HINDPETRO.NS', 'POWERINDIA.NS', 'HUDCO.NS', 'IDFCFIRSTB.NS', 'IRB.NS', 'ITCHOTELS.NS', 'INDIANB.NS', 'IRCTC.NS', 'IREDA.NS', 'IGL.NS', 'INDUSTOWER.NS', 'INDUSINDBK.NS', 'JUBLFOOD.NS', 'KEI.NS', 'KPITTECH.NS', 'KALYANKJIL.NS', 'LTF.NS', 'LICHSGFIN.NS', 'LUPIN.NS', 'MRF.NS', 'M&MFIN.NS', 'MANKIND.NS', 'MARICO.NS', 'MFSL.NS', 'MOTILALOFS.NS', 'MPHASIS.NS', 'MUTHOOTFIN.NS', 'NHPC.NS', 'NMDC.NS', 'NTPCGREEN.NS', 'NATIONALUM.NS', 'OBEROIRLTY.NS', 'OIL.NS', 'PAYTM.NS', 'OFSS.NS', 'POLICYBZR.NS', 'PIIND.NS', 'PAGEIND.NS', 'PATANJALI.NS', 'PERSISTENT.NS', 'PHOENIXLTD.NS', 'POLYCAB.NS', 'PREMIERENE.NS', 'PRESTIGE.NS', 'RVNL.NS', 'SBICARD.NS', 'SRF.NS', 'SONACOMS.NS', 'SAIL.NS', 'SUPREMEIND.NS', 'SUZLON.NS', 'SWIGGY.NS', 'TATACOMM.NS', 'TATAELXSI.NS', 'TATATECH.NS', 'TORNTPOWER.NS', 'TIINDIA.NS', 'UPL.NS', 'UNIONBANK.NS', 'VMM.NS', 'IDEA.NS', 'VOLTAS.NS', 'WAAREEENER.NS', 'YESBANK.NS'
    ],

    // NIFTY SMALLCAP 100 (Major Constituents)
    '^CNXSC': [
        'AADHARHFC.NS', 'AARTIIND.NS', 'ABREL.NS', 'AEGISLOG.NS', 'AEGISVOPAK.NS', 'AFCONS.NS', 'AFFLE.NS', 'ARE&M.NS', 'AMBER.NS', 'ANANDRATHI.NS', 'ANANTRAJ.NS', 'ANGELONE.NS', 'APTUS.NS', 'ASTERDM.NS', 'ATUL.NS', 'BEML.NS', 'BLS.NS', 'BANDHANBNK.NS', 'FIRSTCRY.NS', 'BRIGADE.NS', 'CESC.NS', 'CGCL.NS', 'CASTROLIND.NS', 'CDSL.NS', 'CHAMBLFERT.NS', 'CHOLAHLDNG.NS', 'CAMS.NS', 'CREDITACC.NS', 'CROMPTON.NS', 'CYIENT.NS', 'DATAPATTNS.NS', 'DEEPAKFERT.NS', 'DELHIVERY.NS', 'DEVYANI.NS', 'LALPATHLAB.NS', 'FSL.NS', 'FIVESTAR.NS', 'GRSE.NS', 'GILLETTE.NS', 'GLAND.NS', 'GODIGIT.NS', 'GESHIP.NS', 'HBLENGINE.NS', 'HSCL.NS', 'HINDCOPPER.NS', 'IFCI.NS', 'IIFL.NS', 'IRCON.NS', 'IEX.NS', 'INOXWIND.NS', 'IGIL.NS', 'IKS.NS', 'JBCHEPHARM.NS', 'JBMA.NS', 'JINDALSAW.NS', 'JWL.NS', 'JYOTICNC.NS', 'KAJARIACER.NS', 'KPIL.NS', 'KARURVYSYA.NS', 'KAYNES.NS', 'KEC.NS', 'KFINTECH.NS', 'LAURUSLABS.NS', 'MGL.NS', 'MANAPPURAM.NS', 'MRPL.NS', 'MCX.NS', 'NATCOPHARM.NS', 'NBCC.NS', 'NCC.NS', 'NH.NS', 'NAVINFLUOR.NS', 'NEULANDLAB.NS', 'NEWGEN.NS', 'NUVAMA.NS', 'OLAELEC.NS', 'PCBL.NS', 'PGEL.NS', 'PNBHOUSING.NS', 'PPLPHARMA.NS', 'POONAWALLA.NS', 'RADICO.NS', 'REDINGTON.NS', 'RPOWER.NS', 'SAGILITY.NS', 'SHYAMMETL.NS', 'SIGNATURE.NS', 'STARHEALTH.NS', 'SWANCORP.NS', 'TATACHEM.NS', 'TEJASNET.NS', 'RAMCOCEM.NS', 'TRIDENT.NS', 'TRITURBINE.NS', 'WELCORP.NS', 'WHIRLPOOL.NS', 'WOCKPHARMA.NS', 'ZENTEC.NS', 'ZENSARTECH.NS'
    ],

    // --- SECTORAL ---
    '^NSEBANK': [
        'HDFCBANK.NS', 'ICICIBANK.NS', 'SBIN.NS', 'KOTAKBANK.NS', 'AXISBANK.NS', 'INDUSINDBK.NS', 
        'BANKBARODA.NS', 'PNB.NS', 'IDFCFIRSTB.NS', 'AUBANK.NS', 'FEDERALBNK.NS', 'BANDHANBNK.NS'
    ],
    '^CNXIT': [
        'TCS.NS', 'INFY.NS', 'HCLTECH.NS', 'WIPRO.NS', 'TECHM.NS', 'LTIM.NS', 'PERSISTENT.NS', 'COFORGE.NS', 
        'MPHASIS.NS', 'LTTS.NS'
    ],
    '^CNXAUTO': [
        'MARUTI.NS', 'TATAMOTORS.NS', 'M&M.NS', 'BAJAJ-AUTO.NS', 'EICHERMOT.NS', 'TVSMOTOR.NS', 'HEROMOTOCO.NS', 
        'BHARATFORG.NS', 'ASHOKLEY.NS', 'MOTHERSON.NS', 'MRF.NS', 'BALKRISIND.NS', 'TIINDIA.NS', 'BOSCHLTD.NS'
    ],
    '^CNXMETAL': [
        'TATASTEEL.NS', 'HINDALCO.NS', 'JSWSTEEL.NS', 'VEDL.NS', 'JINDALSTEL.NS', 'SAIL.NS', 'NMDC.NS', 
        'COALINDIA.NS', 'HINDZINC.NS', 'NATIONALUM.NS', 'APLAPOLLO.NS', 'RATNAMANI.NS', 'WELCORP.NS'
    ],
    '^CNXPHARMA': [
        'SUNPHARMA.NS', 'DRREDDY.NS', 'CIPLA.NS', 'DIVISLAB.NS', 'LUPIN.NS', 'AUROPHARMA.NS', 'APOLLOHOSP.NS', 
        'ALKEM.NS', 'TORNTPHARM.NS', 'MANKIND.NS', 'ZYDUSLIFE.NS', 'ABBOTINDIA.NS', 'GLAND.NS', 'LAURUSLABS.NS'
    ],
    '^CNXFMCG': [
        'ITC.NS', 'HINDUNILVR.NS', 'NESTLEIND.NS', 'BRITANNIA.NS', 'TATACONSUM.NS', 'GODREJCP.NS', 'DABUR.NS', 
        'MARICO.NS', 'VBL.NS', 'COLPAL.NS', 'PGHL.NS', 'UBL.NS', 'RADICO.NS', 'EIDPARRY.NS', 'BALRAMCHIN.NS'
    ],
    '^CNXENERGY': [
        'RELIANCE.NS', 'NTPC.NS', 'POWERGRID.NS', 'ONGC.NS', 'BPCL.NS', 'COALINDIA.NS', 'TATAPOWER.NS', 
        'GAIL.NS', 'IOC.NS', 'ADANIGREEN.NS'
    ],
    '^CNXREALTY': [
        'DLF.NS', 'GODREJPROP.NS', 'OBEROIRLTY.NS', 'PHOENIXLTD.NS', 'PRESTIGE.NS', 'BRIGADE.NS', 'SOBHA.NS', 
     'MAHLIFE.NS', 'LODHA.NS'
    ],
    '^CNXMEDIA': [
        'ZEEL.NS', 'SUNTV.NS', 'PVRINOX.NS', 'NAZARA.NS', 'DISHTV.NS', 'HATHWAY.NS', 'NETWORK18.NS', 
        'TV18BRDCST.NS', 'SAREGAMA.NS', 'DBCORP.NS'
    ],
    '^CNXPSUBANK': [
        'SBIN.NS', 'BANKBARODA.NS', 'PNB.NS', 'CANBK.NS', 'UNIONBANK.NS', 'INDIANB.NS', 'BANKINDIA.NS', 
        'IOB.NS', 'CENTRALBK.NS', 'MAHABANK.NS', 'UCOBANK.NS', 'PSB.NS'
    ],
    '^CNXPVTBANK': [
        'HDFCBANK.NS', 'ICICIBANK.NS', 'KOTAKBANK.NS', 'AXISBANK.NS', 'INDUSINDBK.NS', 'FEDERALBNK.NS', 
        'IDFCFIRSTB.NS', 'BANDHANBNK.NS', 'CUB.NS', 'RBLBANK.NS'
    ],
    '^CNXHLTH': [
        'SUNPHARMA.NS', 'DRREDDY.NS', 'DIVISLAB.NS', 'CIPLA.NS', 'APOLLOHOSP.NS', 'MAXHEALTH.NS', 
        'LUPIN.NS', 'AUROPHARMA.NS', 'ALKEM.NS', 'SYNGENE.NS'
    ],
    '^CNXCONSUM': [
        'TITAN.NS', 'HAVELLS.NS', 'VOLTAS.NS', 'DIXON.NS', 'CROMPTON.NS', 'BLUESTARCO.NS', 
        'WHIRLPOOL.NS', 'KAJARIACER.NS', 'RAJESHEXPO.NS', 'TTKPRESTIG.NS'
    ],
    '^CNXFIN': [
        'HDFCBANK.NS', 'ICICIBANK.NS', 'BAJFINANCE.NS', 'SBIN.NS', 'AXISBANK.NS', 'KOTAKBANK.NS', 'BAJAJFINSV.NS',
        'HDFCLIFE.NS', 'SBILIFE.NS', 'CHOLAFIN.NS', 'SHRIRAMFIN.NS', 'ICICIPRULI.NS', 'MUTHOOTFIN.NS', 'SBIcard.NS',
        'RECLTD.NS', 'PFC.NS', 'HDFCAMC.NS', 'BAJAJHLDNG.NS', 'IDFC.NS', 'M&MFIN.NS'
    ]
}