// lib/market-data.ts

export const INDICES = [
    // Benchmark Indices
    { name: 'NIFTY 50', ticker: '^NSEI' },
    { name: 'SENSEX', ticker: '^BSESN' },
    { name: 'INDIA VIX', ticker: '^INDIAVIX' },
    
    // Broader Market
    { name: 'NIFTY MIDCAP 100', ticker: 'NIFTY_MIDCAP_100.NS' },
    { name: 'NIFTY SMALLCAP 100', ticker: '^CNXSC' },

    // Sectoral Indices (From your list)
    { name: 'NIFTY BANK', ticker: '^NSEBANK' },
    { name: 'NIFTY AUTO', ticker: '^CNXAUTO' },
    { name: 'NIFTY IT', ticker: '^CNXIT' },
    { name: 'NIFTY FMCG', ticker: '^CNXFMCG' },
    { name: 'NIFTY METAL', ticker: '^CNXMETAL' },
    { name: 'NIFTY PHARMA', ticker: '^CNXPHARMA' },
    { name: 'NIFTY ENERGY', ticker: '^CNXENERGY' }, // Requested
    { name: 'NIFTY REALTY', ticker: '^CNXREALTY' },
    { name: 'NIFTY MEDIA', ticker: '^CNXMEDIA' },
    { name: 'NIFTY PSU BANK', ticker: '^CNXPSUBANK' },
    { name: 'NIFTY PVT BANK', ticker: 'NIFTY_PVT_BANK.NS' },
    { name: 'NIFTY HEALTHCARE', ticker: 'NIFTY_HEALTHCARE.NS' },
    { name: 'NIFTY CONSUMER DURABLES', ticker: '^CNXCONSUM' },
    { name: 'NIFTY FIN SERVICE', ticker: '^CNXFIN' },
    { name: 'NIFTY COMMODITIES', ticker: '^CNXCMDT'},
    { name: 'NIFTY CAPITAL MARKETS', ticker: 'NIFTY_CAPITAL_MKT.NS'},
    { name: 'NIFTY CHEMICALS', ticker: 'NIFTY_CHEMICALS.NS'},

]

// Full constituent lists for each index
export const SECTOR_CONSTITUENTS: Record<string, string[]> = {
    // --- BENCHMARKS ---
    '^INDIAVIX': [], // VIX has no constituents
    
    // SENSEX (Full 30)
    '^BSESN': [ 
        'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 'INFY.NS', 'HINDUNILVR.NS', 'ITC.NS', 'SBIN.NS', 
        'BHARTIARTL.NS', 'BAJFINANCE.NS', 'LT.NS', 'KOTAKBANK.NS', 'AXISBANK.NS', 'HCLTECH.NS', 'TITAN.NS', 
        'ASIANPAINT.NS', 'MARUTI.NS', 'SUNPHARMA.NS', 'TATASTEEL.NS', 'NTPC.NS', 'ULTRACEMCO.NS', 'POWERGRID.NS', 
        'M&M.NS', 'NESTLEIND.NS', 'TATAMOTORS.NS', 'INDUSINDBK.NS', 'TECHM.NS', 'WIPRO.NS', 'JSWSTEEL.NS', 'BAJAJFINSV.NS'
    ],

    // NIFTY 50 (Full List)
    '^NSEI': [ 
        'ADANIENT.NS', 'ADANIPORTS.NS', 'APOLLOHOSP.NS', 'ASIANPAINT.NS', 'AXISBANK.NS', 'BAJAJ-AUTO.NS', 
        'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'BPCL.NS', 'BHARTIARTL.NS', 'BRITANNIA.NS', 'CIPLA.NS', 'COALINDIA.NS', 
        'DIVISLAB.NS', 'DRREDDY.NS', 'EICHERMOT.NS', 'GRASIM.NS', 'HCLTECH.NS', 'HDFCBANK.NS', 'HDFCLIFE.NS', 
        'HEROMOTOCO.NS', 'HINDALCO.NS', 'HINDUNILVR.NS', 'ICICIBANK.NS', 'ITC.NS', 'INDUSINDBK.NS', 'INFY.NS', 
        'JSWSTEEL.NS', 'KOTAKBANK.NS', 'LTIM.NS', 'LT.NS', 'M&M.NS', 'MARUTI.NS', 'NESTLEIND.NS', 'NTPC.NS', 
        'ONGC.NS', 'POWERGRID.NS', 'RELIANCE.NS', 'SBILIFE.NS', 'SHRIRAMFIN.NS', 'SBIN.NS', 'SUNPHARMA.NS', 
        'TCS.NS', 'TATACONSUM.NS', 'TATAMOTORS.NS', 'TATASTEEL.NS', 'TECHM.NS', 'TITAN.NS', 'ULTRACEMCO.NS', 'WIPRO.NS'
    ],

    // --- BROADER MARKETS ---
    
    // NIFTY MIDCAP 100 (Major High Volume Constituents)
    'NIFTY_MIDCAP_100.NS': [
        '360ONE.NS', 'ACC.NS', 'APLAPOLLO.NS', 'AUBANK.NS', 'ATGL.NS', 'ABCAPITAL.NS', 'ALKEM.NS', 'ASHOKLEY.NS', 'ASTRAL.NS', 'AUROPHARMA.NS', 'BSE.NS', 'BANKINDIA.NS', 'BDL.NS', 'BHARATFORG.NS', 'BHEL.NS', 'BHARTIHEXA.NS', 'BIOCON.NS', 'BLUESTARCO.NS', 'COCHINSHIP.NS', 'COFORGE.NS', 'COLPAL.NS', 'CONCOR.NS', 'COROMANDEL.NS', 'CUMMINSIND.NS', 'DABUR.NS', 'DIXON.NS', 'EXIDEIND.NS', 'NYKAA.NS', 'FEDERALBNK.NS', 'FORTIS.NS', 'GMRAIRPORT.NS', 'GLENMARK.NS', 'GODFRYPHLP.NS', 'GODREJPROP.NS', 'HDFCAMC.NS', 'HEROMOTOCO.NS', 'HINDPETRO.NS', 'POWERINDIA.NS', 'HUDCO.NS', 'IDFCFIRSTB.NS', 'IRB.NS', 'ITCHOTELS.NS', 'INDIANB.NS', 'IRCTC.NS', 'IREDA.NS', 'IGL.NS', 'INDUSTOWER.NS', 'INDUSINDBK.NS', 'JUBLFOOD.NS', 'KEI.NS', 'KPITTECH.NS', 'KALYANKJIL.NS', 'LTF.NS', 'LICHSGFIN.NS', 'LUPIN.NS', 'MRF.NS', 'M&MFIN.NS', 'MANKIND.NS', 'MARICO.NS', 'MFSL.NS', 'MOTILALOFS.NS', 'MPHASIS.NS', 'MUTHOOTFIN.NS', 'NHPC.NS', 'NMDC.NS', 'NTPCGREEN.NS', 'NATIONALUM.NS', 'OBEROIRLTY.NS', 'OIL.NS', 'PAYTM.NS', 'OFSS.NS', 'POLICYBZR.NS', 'PIIND.NS', 'PAGEIND.NS', 'PATANJALI.NS', 'PERSISTENT.NS', 'PHOENIXLTD.NS', 'POLYCAB.NS', 'PREMIERENE.NS', 'PRESTIGE.NS', 'RVNL.NS', 'SBICARD.NS', 'SRF.NS', 'SONACOMS.NS', 'SAIL.NS', 'SUPREMEIND.NS', 'SUZLON.NS', 'SWIGGY.NS', 'TATACOMM.NS', 'TATAELXSI.NS', 'TATATECH.NS', 'TORNTPOWER.NS', 'TIINDIA.NS', 'UPL.NS', 'UNIONBANK.NS', 'VMM.NS', 'IDEA.NS', 'VOLTAS.NS', 'WAAREEENER.NS', 'YESBANK.NS'
    ],

    // NIFTY SMALLCAP 100 (Major Constituents)
    '^CNXSC': [
        'AADHARHFC.NS', 'AARTIIND.NS', 'ABREL.NS', 'AEGISLOG.NS', 'AEGISVOPAK.NS', 'AFCONS.NS', 'AFFLE.NS', 'ARE&M.NS', 'AMBER.NS', 'ANANDRATHI.NS', 'ANANTRAJ.NS', 'ANGELONE.NS', 'APTUS.NS', 'ASTERDM.NS', 'ATUL.NS', 'BEML.NS', 'BLS.NS', 'BANDHANBNK.NS', 'FIRSTCRY.NS', 'BRIGADE.NS', 'CESC.NS', 'CGCL.NS', 'CASTROLIND.NS', 'CDSL.NS', 'CHAMBLFERT.NS', 'CHOLAHLDNG.NS', 'CAMS.NS', 'CREDITACC.NS', 'CROMPTON.NS', 'CYIENT.NS', 'DATAPATTNS.NS', 'DEEPAKFERT.NS', 'DELHIVERY.NS', 'DEVYANI.NS', 'LALPATHLAB.NS', 'FSL.NS', 'FIVESTAR.NS', 'GRSE.NS', 'GILLETTE.NS', 'GLAND.NS', 'GODIGIT.NS', 'GESHIP.NS', 'HBLENGINE.NS', 'HSCL.NS', 'HINDCOPPER.NS', 'IFCI.NS', 'IIFL.NS', 'IRCON.NS', 'IEX.NS', 'INOXWIND.NS', 'IGIL.NS', 'IKS.NS', 'JBCHEPHARM.NS', 'JBMA.NS', 'JINDALSAW.NS', 'JWL.NS', 'JYOTICNC.NS', 'KAJARIACER.NS', 'KPIL.NS', 'KARURVYSYA.NS', 'KAYNES.NS', 'KEC.NS', 'KFINTECH.NS', 'LAURUSLABS.NS', 'MGL.NS', 'MANAPPURAM.NS', 'MRPL.NS', 'MCX.NS', 'NATCOPHARM.NS', 'NBCC.NS', 'NCC.NS', 'NH.NS', 'NAVINFLUOR.NS', 'NEULANDLAB.NS', 'NEWGEN.NS', 'NUVAMA.NS', 'OLAELEC.NS', 'PCBL.NS', 'PGEL.NS', 'PNBHOUSING.NS', 'PPLPHARMA.NS', 'POONAWALLA.NS', 'RADICO.NS', 'REDINGTON.NS', 'RPOWER.NS', 'SAGILITY.NS', 'SHYAMMETL.NS', 'SIGNATURE.NS', 'STARHEALTH.NS', 'SWANCORP.NS', 'TATACHEM.NS', 'TEJASNET.NS', 'RAMCOCEM.NS', 'TRIDENT.NS', 'TRITURBINE.NS', 'WELCORP.NS', 'WHIRLPOOL.NS', 'WOCKPHARMA.NS', 'ZENTEC.NS', 'ZENSARTECH.NS'
    ],

    // --- SECTORAL ---
    '^NSEBANK': [
        'AUBANK.NS', 'AXISBANK.NS', 'BANKBARODA.NS', 'CANBK.NS', 'FEDERALBNK.NS', 'HDFCBANK.NS',
        'ICICIBANK.NS', 'IDFCFIRSTB.NS', 'INDUSINDBK.NS', 'KOTAKBANK.NS', 'PNB.NS', 'SBIN.NS'
    ],

    '^CNXIT': [
        'COFORGE.NS', 'HCLTECH.NS', 'INFY.NS', 'LTIM.NS', 'MPHASIS.NS', 'OFSS.NS',
        'PERSISTENT.NS', 'TCS.NS', 'TECHM.NS', 'WIPRO.NS'
    ],

    '^CNXAUTO': [
        'ASHOKLEY.NS', 'BAJAJ-AUTO.NS', 'BHARATFORG.NS', 'BOSCHLTD.NS', 'EICHERMOT.NS',
        'EXIDEIND.NS', 'HEROMOTOCO.NS', 'M&M.NS', 'MARUTI.NS', 'MOTHERSON.NS',
        'SONACOMS.NS', 'TVSMOTOR.NS', 'TMPV.NS', 'TIINDIA.NS', 'UNOMINDA.NS'
    ],

    '^CNXMETAL': [
        'APLAPOLLO.NS', 'ADANIENT.NS', 'HINDALCO.NS', 'HINDCOPPER.NS', 'HINDZINC.NS',
        'JSWSTEEL.NS', 'JSL.NS', 'JINDALSTEL.NS', 'LLOYDSME.NS', 'NMDC.NS',
        'NATIONALUM.NS', 'SAIL.NS', 'TATASTEEL.NS', 'VEDL.NS', 'WELCORP.NS'
    ],

    '^CNXPHARMA': [
        'ABBOTINDIA.NS', 'AJANTPHARM.NS', 'ALKEM.NS', 'AUROPHARMA.NS', 'BIOCON.NS',
        'CIPLA.NS', 'DIVISLAB.NS', 'DRREDDY.NS', 'GLAND.NS', 'GLENMARK.NS',
        'IPCALAB.NS', 'JBCHEPHARM.NS', 'LAURUSLABS.NS', 'LUPIN.NS', 'MANKIND.NS',
        'PPLPHARMA.NS', 'SUNPHARMA.NS', 'TORNTPHARM.NS', 'WOCKPHARMA.NS', 'ZYDUSLIFE.NS'
    ],

    '^CNXFMCG': [
        'BRITANNIA.NS', 'COLPAL.NS', 'DABUR.NS', 'EMAMILTD.NS', 'GODREJCP.NS',
        'HINDUNILVR.NS', 'ITC.NS', 'MARICO.NS', 'NESTLEIND.NS', 'PATANJALI.NS',
        'RADICO.NS', 'TATACONSUM.NS', 'UBL.NS', 'UNITDSPR.NS', 'VBL.NS'
    ],

    '^CNXENERGY': [
        'ABB.NS', 'ADANIENSOL.NS', 'ADANIGREEN.NS', 'ADANIPOWER.NS', 'ATGL.NS',
        'AEGISLOG.NS', 'BHEL.NS', 'BPCL.NS', 'CESC.NS', 'CGPOWER.NS',
        'CASTROLIND.NS', 'COALINDIA.NS', 'GAIL.NS', 'GVT&D.NS', 'GUJGASLTD.NS',
        'GSPL.NS', 'HINDPETRO.NS', 'POWERINDIA.NS', 'IOC.NS', 'IGL.NS',
        'INOXWIND.NS', 'JSWENERGY.NS', 'JPPOWER.NS', 'MGL.NS', 'NHPC.NS',
        'NLCINDIA.NS', 'NTPC.NS', 'ONGC.NS', 'OIL.NS', 'PETRONET.NS',
        'POWERGRID.NS', 'RELIANCE.NS', 'RPOWER.NS', 'SJVN.NS', 'ENRIN.NS',
        'SIEMENS.NS', 'SUZLON.NS', 'TATAPOWER.NS', 'THERMAX.NS', 'TORNTPOWER.NS'
    ],

    '^CNXREALTY': [
        'ANANTRAJ.NS', 'BRIGADE.NS', 'DLF.NS', 'GODREJPROP.NS', 'LODHA.NS',
        'OBEROIRLTY.NS', 'PHOENIXLTD.NS', 'PRESTIGE.NS', 'SIGNATURE.NS', 'SOBHA.NS'
    ],

    '^CNXMEDIA': [
        'DBCORP.NS', 'HATHWAY.NS', 'NAZARA.NS', 'NETWORK18.NS', 'PVRINOX.NS',
        'PFOCUS.NS', 'SAREGAMA.NS', 'SUNTV.NS', 'TIPSMUSIC.NS', 'ZEEL.NS'
    ],

    '^CNXPSUBANK': [
        'BANKBARODA.NS', 'BANKINDIA.NS', 'MAHABANK.NS', 'CANBK.NS', 'CENTRALBK.NS',
        'INDIANB.NS', 'IOB.NS', 'PSB.NS', 'PNB.NS', 'SBIN.NS',
        'UCOBANK.NS', 'UNIONBANK.NS'
    ],

    'NIFTY_PVT_BANK.NS': [
        'HDFCBANK.NS', 'ICICIBANK.NS', 'AXISBANK.NS', 'KOTAKBANK.NS',
        'INDUSINDBK.NS', 'FEDERALBNK.NS', 'IDFCFIRSTB.NS',
        'BANDHANBNK.NS', 'RBLBANK.NS', 'YESBANK.NS'
    ],

    'NIFTY_HEALTHCARE.NS': [
        'APOLLOHOSP.NS', 'ASIANPAINT.NS', 'CIPLA.NS', 'DIVISLAB.NS',
        'DRREDDY.NS', 'FORTIS.NS', 'LALPATHLAB.NS', 'MAXHEALTH.NS',
        'METROPOLIS.NS', 'PFIZER.NS', 'SUNPHARMA.NS', 'TORNTPHARM.NS'
    ],

    '^CNXCONSUM': [
        'AMBER.NS', 'BAJAJELEC.NS', 'BHARATFORG.NS', 'CROMPTON.NS',
        'DIXON.NS', 'HAVELLS.NS', 'KAJARIACER.NS', 'METROPOLIS.NS',
        'RAJESHEXPO.NS', 'TITAN.NS', 'TTKPRESTIG.NS', 'VOLTAS.NS',
        'WHIRLPOOL.NS'
    ],

    '^CNXFIN': [
        'HDFCBANK.NS', 'ICICIBANK.NS', 'BAJFINANCE.NS', 'SBIN.NS', 'AXISBANK.NS', 
        'KOTAKBANK.NS', 'BAJAJFINSV.NS', 'HDFCLIFE.NS', 'SBILIFE.NS', 'CHOLAFIN.NS',
        'SHRIRAMFIN.NS', 'ICICIPRULI.NS', 'MUTHOOTFIN.NS', 'SBIcard.NS',
        'RECLTD.NS', 'PFC.NS', 'HDFCAMC.NS', 'BAJAJHLDNG.NS', 'IDFCFIRSTB.NS', 'M&MFIN.NS'
    ],

    '^CNXCMDT': [
        'ADANIENT.NS', 'ALKEM.NS', 'APOLLOTYRE.NS', 'ASHOKLEY.NS', 'ASIANPAINT.NS',
        'AUROPHARMA.NS', 'BERGEPAINT.NS', 'BRITANNIA.NS', 'CHAMBLFERT.NS',
        'COALINDIA.NS', 'CUMMINSIND.NS', 'DIVISLAB.NS', 'GRASIM.NS', 'HINDZINC.NS',
        'HINDALCO.NS', 'ITC.NS', 'JINDALSTEL.NS', 'JSWSTEEL.NS', 'LT.NS',
        'TATASTEEL.NS', 'NMDC.NS', 'NATIONALUM.NS'
    ],

    'NIFTY_CAPITAL_MKT.NS': [
        'CAMS.NS', 'CDSL.NS', 'HDFCAMC.NS', 'ISEC.NS', 'KFINTECH.NS',
        'MCX.NS', 'PFS.NS', 'RECLTD.NS', 'SBICARD.NS', 'PFC.NS', 'UTIAMC.NS'
    ],

    'NIFTY_CHEMICALS.NS': [
        'AARTIIND.NS', 'ALKYLAMINE.NS', 'ATUL.NS', 'COROMANDEL.NS',
        'DEEPAKNTR.NS', 'GODREJIND.NS', 'GNFC.NS', 'FLUOROCHEM.NS',
        'JUBLINGREA.NS', 'NAVINFLUOR.NS', 'PIIND.NS', 'PRAJIND.NS',
        'SOLARINDS.NS', 'TATACHEM.NS', 'UPL.NS'
    ],
}